### ISSUE TITLE
ひとりごと投稿ページのデザインを整える

### ISSUE THREAD

**Issue by Kaito1290** [ok-os-job-change-team/kaito-twitter-clone-bootcamp#62]
### ひとりごと投稿ページ
- ログインユーザーの情報を表示する
- 投稿に成功したら、ひとりごと一覧ページに遷移する
- 投稿に失敗したら、エラーメッセージを表示する
- キャンセルボタンを押したら、マイページに遷移する
**＜完成イメージ＞**
![ひとりごと投稿ページ](https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/assets/90958196/925979ef-b584-4a89-a94b-e8b95b9c66d6)

**Comment by ochi-sho-private-study** [comment]
独り言に対して、カテゴリを紐づけることができて、
カテゴリ分けができるようになると、Twitterとの差別化ができそう。
