### ISSUE TITLE
READMEにdemo動画を追加する

### ISSUE THREAD

**Issue by ochi-sho-private-study** [ok-os-job-change-team/kaito-twitter-clone-bootcamp#93]
### ゴール
- アプリのデモ動画を追加する

**Comment by Kaito1290** [comment]
https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/issues/39とissuseの内容が重複しているのでcloseしました。

**Comment by Kaito1290** [comment]
アプリのデモ動画の追加は、フロントエンドのPR対応後となるため

**Comment by Kaito1290** [comment]
アップロード用
![demo動画_230229](https://github.com/ok-os-job-change-team/kaito-twitter-clone-bootcamp/assets/90958196/6468e15b-1e46-4961-a419-f4ea7e8778c1)
